#!/bin/bash
set -euo pipefail

# ==============================================================================
# CADDY PROXY + MANAGER — Management Script
# Single entry point for installing, starting, updating, and uninstalling
# Caddy reverse proxy together with CaddyManager Web UI.
#
# Usage:
#   bash caddy.sh                                 (local, interactive)
#   curl -fsSL <raw_url>/caddy.sh | bash           (remote, automatic)
#
# Re-running this script on an existing installation is safe.
# ==============================================================================

GIT_BRANCH="${GIT_BRANCH:-main}"
REPO_BASE="${REPO_BASE:-https://raw.githubusercontent.com/Carlosjcfr/docker-develop/$GIT_BRANCH}"
REPO_RAW="$REPO_BASE/projects/caddy-proxy-manager"

# =============================================================================
# SHARED LIBRARY
# Source common functions: logging, guards, env bootstrap, validation.
# Set LIB_LOCAL to an absolute path to use a local copy (development only).
# =============================================================================

_LIB_URL="$REPO_BASE/lib/lib.sh"
# shellcheck source=../../lib/lib.sh
if [[ -n "${LIB_LOCAL:-}" && -f "$LIB_LOCAL" ]]; then
    source "$LIB_LOCAL"
else
    source <(curl -fsSL "$_LIB_URL") || {
        echo "[ERROR] Could not download shared library from: $_LIB_URL" >&2
        echo "        Check your network connection and try again." >&2
        exit 1
    }
fi
unset _LIB_URL

# =============================================================================
# SERVICE-SPECIFIC FUNCTIONS
# =============================================================================

# Returns 0 if an existing Caddy installation is detected, 1 otherwise.
check_existing_installation() {
    local dir="${1:-/opt/caddy}"
    if [ -f "$dir/.env" ] && podman container exists caddy 2>/dev/null; then
        return 0
    fi
    return 1
}

load_configuration() {
    # shellcheck source=/dev/null
    source "$TMP_DIR/config.env"

    # Security guard: abort if a secret key is found in the repo config file
    check_secrets_not_in_config "$TMP_DIR/config.env" JWT_SECRET

    INSTALL_DIR="${INSTALL_DIR:-/opt/caddy}"
    CADDY_VERSION="${CADDY_VERSION:-2.11-alpine}"
    ACME_EMAIL="${ACME_EMAIL:-you@example.com}"
    PACKAGE_VERSION="${PACKAGE_VERSION:-0.0.2}"
    CADDYMANAGER_UI_PORT="${CADDYMANAGER_UI_PORT:-8080}"
    APP_NAME="${APP_NAME:-Caddy Manager}"
    DARK_MODE="${DARK_MODE:-true}"
    BACKEND_PORT="${BACKEND_PORT:-3000}"
    DB_ENGINE="${DB_ENGINE:-sqlite}"
    JWT_EXPIRATION="${JWT_EXPIRATION:-24h}"
    LOG_LEVEL="${LOG_LEVEL:-info}"
    AUDIT_LOG_MAX_SIZE_MB="${AUDIT_LOG_MAX_SIZE_MB:-100}"
    AUDIT_LOG_RETENTION_DAYS="${AUDIT_LOG_RETENTION_DAYS:-90}"
    PING_INTERVAL="${PING_INTERVAL:-30000}"
    PING_TIMEOUT="${PING_TIMEOUT:-2000}"
    METRICS_HISTORY_MAX="${METRICS_HISTORY_MAX:-1000}"

    log "Configuration loaded (INSTALL_DIR=$INSTALL_DIR, UI_PORT=$CADDYMANAGER_UI_PORT)."
}

generate_runtime_env() {
    log "Generating runtime .env file..."
    local OLD_UMASK
    OLD_UMASK=$(umask)
    umask 177

    CORS_ORIGIN="http://$HOST_IP:$CADDYMANAGER_UI_PORT"

    cat <<EOF > "$INSTALL_DIR/.env"
# =============================================================================
# CADDY PROXY + MANAGER — Runtime Environment Variables
# Auto-generated by caddy.sh — do NOT edit manually.
# To change settings, edit config.env in the repository and re-run caddy.sh.
# =============================================================================

# --- Core (auto-generated) ---
HOST_IP="$HOST_IP"
PUID="$PUID"
PGID="$PGID"
PODMAN_SOCK="$PODMAN_SOCK"

# --- Caddy Proxy ---
CADDY_VERSION="$CADDY_VERSION"

# --- CaddyManager UI ---
PACKAGE_VERSION="$PACKAGE_VERSION"
CADDYMANAGER_UI_PORT="$CADDYMANAGER_UI_PORT"
APP_NAME="$APP_NAME"
DARK_MODE="$DARK_MODE"

# --- CaddyManager Backend ---
BACKEND_PORT="$BACKEND_PORT"
DB_ENGINE="$DB_ENGINE"
CORS_ORIGIN="$CORS_ORIGIN"
JWT_SECRET="$JWT_SECRET"
JWT_EXPIRATION="$JWT_EXPIRATION"

# --- Logging & Audit ---
LOG_LEVEL="$LOG_LEVEL"
AUDIT_LOG_MAX_SIZE_MB="$AUDIT_LOG_MAX_SIZE_MB"
AUDIT_LOG_RETENTION_DAYS="$AUDIT_LOG_RETENTION_DAYS"

# --- Health Checks ---
PING_INTERVAL="$PING_INTERVAL"
PING_TIMEOUT="$PING_TIMEOUT"

# --- Metrics ---
METRICS_HISTORY_MAX="$METRICS_HISTORY_MAX"
EOF

    umask "$OLD_UMASK"
    log ".env file ready (permissions 600)."
}

prepare_directories() {
    log "Preparing installation directory: $INSTALL_DIR"
    check_install_dir_writable "$INSTALL_DIR"
    mkdir -p "$INSTALL_DIR"

    mv -f "$TMP_DIR/config.env"         "$INSTALL_DIR/config.env"
    mv -f "$TMP_DIR/docker-compose.yml" "$INSTALL_DIR/docker-compose.yml"

    # Caddyfile: only place on first install — preserve user customizations on updates
    if [ ! -f "$INSTALL_DIR/Caddyfile" ]; then
        mv "$TMP_DIR/Caddyfile" "$INSTALL_DIR/Caddyfile"
        log "Default Caddyfile placed in $INSTALL_DIR/"
    else
        log "Existing Caddyfile preserved (not overwritten)."
    fi

    mkdir -p "$INSTALL_DIR/site"
    log "Directories ready."
}

deploy_and_persist() {
    log "Starting services with podman-compose..."
    cd "$INSTALL_DIR"
    # podman-compose up -d exits 0 even on total failure — verify_containers_running
    # performs the real post-deploy check.
    podman-compose up -d

    verify_containers_running caddy caddymanager-backend caddymanager-frontend

    log "Configuring systemd service for persistence..."
    mkdir -p ~/.config/systemd/user/

    cat <<EOF > ~/.config/systemd/user/caddy-compose.service
[Unit]
Description=Caddy Proxy + CaddyManager (podman-compose)
Wants=network-online.target
After=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=$INSTALL_DIR
ExecStart=$(command -v podman-compose) up -d
ExecStop=$(command -v podman-compose) down
TimeoutStartSec=120
TimeoutStopSec=30
Restart=on-failure
RestartSec=15

[Install]
WantedBy=default.target
EOF

    systemctl --user daemon-reload
    systemctl --user enable --now caddy-compose.service
}

print_success() {
    echo ""
    echo "================================================================="
    echo " CADDY PROXY + MANAGER deployed and secured with systemd."
    echo ""
    echo " Caddy Proxy:     http://$HOST_IP (ports 80, 443)"
    echo " CaddyManager UI: http://$HOST_IP:$CADDYMANAGER_UI_PORT"
    echo ""
    echo " Default login: admin / caddyrocks (change after first login!)"
    echo ""
    echo " The services will persist after logout and on VM reboots."
    echo ""
    echo " Useful commands:"
    echo "   Status:  systemctl --user status caddy-compose.service"
    echo "   Logs:    podman logs -f caddy"
    echo "   Restart: systemctl --user restart caddy-compose.service"
    echo "================================================================="
}

# =============================================================================
# ACTIONS
# =============================================================================

do_install() {
    echo ""
    echo "=== CADDY: Fresh Installation ==="
    echo ""

    download_repo_files "$REPO_RAW" config.env docker-compose.yml Caddyfile
    offer_interactive_mode
    load_configuration
    detect_host_ip
    manage_credentials "$INSTALL_DIR" JWT_SECRET
    setup_lingering_and_socket
    enable_privileged_ports
    prepare_directories
    generate_runtime_env
    deploy_and_persist
    print_success
}

do_start() {
    echo ""
    echo "=== CADDY: Starting ==="
    echo ""

    if systemctl --user is-active --quiet caddy-compose.service 2>/dev/null; then
        log "Caddy services are already running."
    else
        systemctl --user start caddy-compose.service
        log "Caddy services started successfully."
    fi

    if [ -f /opt/caddy/.env ]; then
        local ip ui_port
        ip=$(grep "^HOST_IP=" /opt/caddy/.env | cut -d '=' -f2- || echo "unknown")
        ui_port=$(grep "^CADDYMANAGER_UI_PORT=" /opt/caddy/.env | cut -d '=' -f2- || echo "8080")
        log "CaddyManager UI: http://$ip:$ui_port"
    fi
}

do_update() {
    echo ""
    echo "=== CADDY: Updating ==="
    echo ""

    download_repo_files "$REPO_RAW" config.env docker-compose.yml Caddyfile
    offer_interactive_mode
    load_configuration
    detect_host_ip
    manage_credentials "$INSTALL_DIR" JWT_SECRET
    setup_lingering_and_socket
    enable_privileged_ports
    prepare_directories
    generate_runtime_env

    log "Pulling latest images..."
    cd "$INSTALL_DIR"
    podman-compose pull

    deploy_and_persist
    print_success
}

do_uninstall() {
    echo ""
    echo "=== CADDY: Uninstall ==="
    echo ""
    echo " WARNING: This will permanently remove:"
    echo "   - All Caddy containers (caddy, caddymanager-backend, caddymanager-frontend)"
    echo "   - The systemd persistence service"
    echo "   - Container images"
    echo ""

    if [ "$FORCE_YES" -eq 1 ]; then
        CONFIRM="UNINSTALL"
    else
        read -rp " Type 'UNINSTALL' to confirm: " CONFIRM
    fi
    if [ "$CONFIRM" != "UNINSTALL" ]; then
        log "Uninstall cancelled."
        exit 0
    fi

    echo ""
    log "Stopping services..."
    systemctl --user stop caddy-compose.service 2>/dev/null || true
    systemctl --user disable caddy-compose.service 2>/dev/null || true
    rm -f ~/.config/systemd/user/caddy-compose.service
    systemctl --user daemon-reload

    log "Removing containers..."
    podman rm -f caddy caddymanager-backend caddymanager-frontend 2>/dev/null || true

    log "Removing images..."
    podman rmi "docker.io/lucaslorentz/caddy-docker-proxy:${CADDY_VERSION:-2.11-alpine}" 2>/dev/null || true
    podman rmi "docker.io/caddymanager/caddymanager-backend:${PACKAGE_VERSION:-0.0.2}" 2>/dev/null || true
    podman rmi "docker.io/caddymanager/caddymanager-frontend:${PACKAGE_VERSION:-0.0.2}" 2>/dev/null || true

    echo ""
    echo " Persistent volumes:"
    echo "   - caddy_data          (TLS certificates — CRITICAL to preserve!)"
    echo "   - caddy_config        (runtime config)"
    echo "   - caddymanager_sqlite (CaddyManager database)"
    echo ""
    if [ "$FORCE_YES" -eq 1 ]; then
        DELETE_DATA="y"
    else
        read -rp " Delete ALL persistent volumes? (WARNING: TLS certs will be lost!) [y/N]: " DELETE_DATA
    fi
    if [[ "$DELETE_DATA" =~ ^[Yy]$ ]]; then
        log "Removing volumes..."
        podman volume rm caddy_data caddy_config caddymanager_sqlite 2>/dev/null || true
        log "Volumes removed."
    else
        log "Volumes preserved."
    fi

    if [ "$FORCE_YES" -eq 1 ]; then
        DELETE_CONFIG="y"
    else
        read -rp " Delete configuration files ($INSTALL_DIR)? [y/N]: " DELETE_CONFIG
    fi
    if [[ "$DELETE_CONFIG" =~ ^[Yy]$ ]]; then
        rm -rf "${INSTALL_DIR:?}/.env" "${INSTALL_DIR:?}/config.env" \
               "${INSTALL_DIR:?}/docker-compose.yml" "${INSTALL_DIR:?}/site"
        log "Config files removed."
    else
        log "Config files preserved."
    fi

    echo ""
    echo "================================================================="
    echo " CADDY has been uninstalled."
    echo "================================================================="
}

# =============================================================================
# MAIN
# =============================================================================

root_protection
check_dependencies curl podman-compose

parse_args "$@"

if [ -n "$CMD_ACTION" ]; then
    case "$CMD_ACTION" in
        install)   do_install ;;
        start)     do_start ;;
        update)    do_update ;;
        uninstall) do_uninstall ;;
        *) err "Invalid action."; exit 1 ;;
    esac
    exit 0
fi

if check_existing_installation "/opt/caddy"; then
    if [ -t 0 ] && [ "$FORCE_YES" -eq 0 ]; then
        echo ""
        echo "================================================================="
        echo " CADDY PROXY + MANAGER — Management"
        echo "================================================================="
        echo " Existing installation detected at /opt/caddy"
        echo ""
        echo "   1) Start      — Start the existing services"
        echo "   2) Update     — Download latest config and redeploy"
        echo "   3) Uninstall  — Remove containers, service, and data"
        echo "   0) Cancel"
        echo ""
        read -rp " Select [0-3]: " ACTION

        case "$ACTION" in
            1) do_start ;;
            2) do_update ;;
            3) do_uninstall ;;
            0) log "Cancelled."; exit 0 ;;
            *) err "Invalid option."; exit 1 ;;
        esac
    else
        log "Existing installation detected. Running automatic update..."
        do_update
    fi
else
    do_install
fi
