#!/bin/bash
set -euo pipefail

# ==============================================================================
# CADDY PROXY + MANAGER — Interactive Configuration Assistant
# Prompts for each configurable option and generates a local config.env.
# Called automatically by caddy.sh when interactive mode is selected.
#
# Usage (standalone):  bash configure.sh [base_config_env_path]
# Usage (from caddy):  called internally — do not run manually.
# ==============================================================================

# Base config.env to read defaults from (passed as argument or current dir)
BASE_CONFIG="${1:-config.env}"

# --- Load defaults from base config.env if available --------------------------
INSTALL_DIR="/opt/caddy"
HOST_IP=""
CADDY_VERSION="ci-alpine"
ACME_EMAIL="you@example.com"
PACKAGE_VERSION="latest"
CADDYMANAGER_UI_PORT="8080"
APP_NAME="Caddy Manager"
DARK_MODE="true"
BACKEND_PORT="3000"
DB_ENGINE="sqlite"
JWT_EXPIRATION="24h"
LOG_LEVEL="info"
AUDIT_LOG_MAX_SIZE_MB="100"
AUDIT_LOG_RETENTION_DAYS="90"
PING_INTERVAL="30000"
PING_TIMEOUT="2000"
METRICS_HISTORY_MAX="1000"

if [ -f "$BASE_CONFIG" ]; then
    # shellcheck source=/dev/null
    source "$BASE_CONFIG"
fi

# --- Helper: prompt with default value ----------------------------------------
ask() {
    local prompt="$1"
    local default="$2"
    local value

    if [ -n "$default" ]; then
        read -rp "  $prompt [$default]: " value
    else
        read -rp "  $prompt: " value
    fi
    echo "${value:-$default}"
}

# --- Interactive prompts ------------------------------------------------------
echo ""
echo "================================================================="
echo " CADDY PROXY + MANAGER - Interactive Configuration"
echo "================================================================="
echo " Press ENTER to accept the default value shown in brackets."
echo ""

echo " ── Deployment ──"
INSTALL_DIR=$(ask "Installation directory" "$INSTALL_DIR")
HOST_IP=$(ask "Host IP (empty = auto-detect)" "$HOST_IP")

echo ""
echo " ── Caddy Proxy ──"
CADDY_VERSION=$(ask "Caddy image version tag" "$CADDY_VERSION")
ACME_EMAIL=$(ask "ACME email (Let's Encrypt notifications)" "$ACME_EMAIL")

echo ""
echo " ── CaddyManager UI ──"
PACKAGE_VERSION=$(ask "CaddyManager image version tag" "$PACKAGE_VERSION")
CADDYMANAGER_UI_PORT=$(ask "Web UI port" "$CADDYMANAGER_UI_PORT")
APP_NAME=$(ask "Application display name" "$APP_NAME")
DARK_MODE=$(ask "Dark mode (true/false)" "$DARK_MODE")

echo ""
echo " ── CaddyManager Backend ──"
BACKEND_PORT=$(ask "Internal backend API port" "$BACKEND_PORT")
DB_ENGINE=$(ask "Database engine (sqlite/mongodb)" "$DB_ENGINE")
JWT_EXPIRATION=$(ask "JWT token expiration" "$JWT_EXPIRATION")

echo ""
echo " ── Logging & Audit ──"
LOG_LEVEL=$(ask "Log level (debug/info/warn/error)" "$LOG_LEVEL")
AUDIT_LOG_MAX_SIZE_MB=$(ask "Audit log max size (MB)" "$AUDIT_LOG_MAX_SIZE_MB")
AUDIT_LOG_RETENTION_DAYS=$(ask "Audit log retention (days)" "$AUDIT_LOG_RETENTION_DAYS")

echo ""
echo " ── Health Checks & Metrics ──"
PING_INTERVAL=$(ask "Ping interval (ms)" "$PING_INTERVAL")
PING_TIMEOUT=$(ask "Ping timeout (ms)" "$PING_TIMEOUT")
METRICS_HISTORY_MAX=$(ask "Metrics history max snapshots" "$METRICS_HISTORY_MAX")

# --- Write config.env ---------------------------------------------------------
OUTPUT_DIR="$(dirname "$BASE_CONFIG")"
OUTPUT_FILE="${OUTPUT_DIR}/config.env"

cat <<EOF > "$OUTPUT_FILE"
# =============================================================================
# CADDY PROXY + MANAGER — Configuration
# =============================================================================
# Generated by configure.sh (interactive mode).
#
# ⚠️ DO NOT ADD SECRETS HERE — this file is public.
#    JWT_SECRET is auto-generated by caddy.sh.
# =============================================================================

# --- Deployment ---------------------------------------------------------------

INSTALL_DIR=$INSTALL_DIR
HOST_IP=$HOST_IP

# --- Caddy Proxy --------------------------------------------------------------

CADDY_VERSION=$CADDY_VERSION
ACME_EMAIL=$ACME_EMAIL

# --- CaddyManager UI ---------------------------------------------------------

PACKAGE_VERSION=$PACKAGE_VERSION
CADDYMANAGER_UI_PORT=$CADDYMANAGER_UI_PORT
APP_NAME=$APP_NAME
DARK_MODE=$DARK_MODE

# --- CaddyManager Backend ----------------------------------------------------

BACKEND_PORT=$BACKEND_PORT
DB_ENGINE=$DB_ENGINE
JWT_EXPIRATION=$JWT_EXPIRATION

# --- Logging & Audit ----------------------------------------------------------

LOG_LEVEL=$LOG_LEVEL
AUDIT_LOG_MAX_SIZE_MB=$AUDIT_LOG_MAX_SIZE_MB
AUDIT_LOG_RETENTION_DAYS=$AUDIT_LOG_RETENTION_DAYS

# --- Health Checks & Metrics --------------------------------------------------

PING_INTERVAL=$PING_INTERVAL
PING_TIMEOUT=$PING_TIMEOUT
METRICS_HISTORY_MAX=$METRICS_HISTORY_MAX
EOF

echo ""
echo "================================================================="
echo " Configuration saved. Continuing with installation..."
echo "================================================================="
echo ""
