services:
  wallos:
    image: bellamy/wallos:${WALLOS_VERSION}
    container_name: wallos
    restart: unless-stopped
    ports:
      - "${WALLOS_PORT}:80"
    environment:
      - TZ=Europe/Madrid
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ./db:/var/www/html/db:Z
      - ./logos:/var/www/html/images/uploads/logos:Z
    labels:
      - "dev.arcane.icon=${ARCANE_ICON}"
      - "dev.arcane.category=${ARCANE_CATEGORY}"
      - "com.docker.compose.project=wallos"
      - "com.docker.compose.project.working_dir=/app/data/projects/wallos"
