#!/bin/bash
# ==============================================================================
# build.sh - Compiles lib/src/*.sh into a single lib/lib.sh
# ==============================================================================

# Ensure we are executing from the script's directory (lib/)
cd "$(dirname "$0")" || { echo "Failed to enter lib/ directory."; exit 1; }

OUT_FILE="lib.sh"

echo "#!/bin/bash" > "$OUT_FILE"
echo "# ==============================================================================" >> "$OUT_FILE"
echo "# ### DO NOT EDIT THIS FILE. AUTOGENERATED FROM lib/src/ ###" >> "$OUT_FILE"
echo "# ### Modify the source files in lib/src/*.sh and run ./build.sh ###" >> "$OUT_FILE"
echo "# ==============================================================================" >> "$OUT_FILE"
echo "" >> "$OUT_FILE"

# Define the numerical array of modules to ensure order
MODULES=(
    "src/01_core.sh"
    "src/02_install.sh"
    "src/03_health.sh"
    "src/04_uninstall.sh"
    "src/05_arcane.sh"
)

# Append each module to the output file
for mod in "${MODULES[@]}"; do
    if [ ! -f "$mod" ]; then
        echo "Error: Module source not found: $mod"
        exit 1
    fi
    echo "# ==========================================" >> "$OUT_FILE"
    echo "# MODULE: $mod" >> "$OUT_FILE"
    echo "# ==========================================" >> "$OUT_FILE"
    cat "$mod" >> "$OUT_FILE"
    echo "" >> "$OUT_FILE"
done

# Ensure the final compiled file has execution permissions, though not strictly required
chmod +x "$OUT_FILE"

echo "✅ lib.sh has been successfully compiled from sources!"
