#!/bin/bash
# ==============================================================================
# ### DO NOT EDIT THIS FILE. AUTOGENERATED FROM lib/src/ ###
# ### Modify the source files in lib/src/*.sh and run ./build.sh ###
# ==============================================================================

# ==========================================
# MODULE: src/01_core.sh
# ==========================================
# =============================================================================
# LOGGING
# =============================================================================

log()  { echo "[$(date -u '+%H:%M:%S')] [INFO]  $*"; }
warn() { echo "[$(date -u '+%H:%M:%S')] [WARN]  $*" >&2; }
err()  { echo "[$(date -u '+%H:%M:%S')] [ERROR] $*" >&2; }

# =============================================================================
# GUARDS
# =============================================================================

# Enforces rootless execution (Ref: docs/LIBRARY_REFERENCE.md)
root_protection() {
    if [[ $EUID -eq 0 ]]; then
        echo "-----------------------------------------------------------------"
        echo " ERROR: DO NOT RUN THIS SCRIPT WITH SUDO"
        echo "-----------------------------------------------------------------"
        echo " Rootless Podman requires a normal user session."
        echo " Please retry WITHOUT sudo."
        echo "-----------------------------------------------------------------"
        exit 1
    fi
}

# Verifies required commands exist in PATH (Ref: docs/LIBRARY_REFERENCE.md)
check_dependencies() {
    for cmd in "$@"; do
        if ! command -v "$cmd" &>/dev/null; then
            err "Required command '$cmd' not found. Please install it before continuing."
            exit 1
        fi
    done
}

# Ensures no secret keys are hardcoded in config files (Ref: docs/LIBRARY_REFERENCE.md)
check_secrets_not_in_config() {
    local config_file="${1:?check_secrets_not_in_config requires a config file path}"
    shift
    for secret_name in "$@"; do
        if grep -q "^${secret_name}=" "$config_file"; then
            echo "-----------------------------------------------------------------"
            echo " ERROR: SECRET DETECTED IN config.env"
            echo "-----------------------------------------------------------------"
            echo " '$secret_name' must NEVER be stored in the repository."
            echo " Remove it from config.env — secrets are auto-generated at runtime."
            echo "-----------------------------------------------------------------"
            exit 1
        fi
    done
}

# Validates or creates the installation directory with elevated permissions if needed (Ref: docs/LIBRARY_REFERENCE.md)
check_install_dir_writable() {
    local dir="${1:?check_install_dir_writable requires a directory argument}"
    
    # Intenta crear como usuario normal. Si falla o no es escribible, escalamos a sudo.
    if ! mkdir -p "$dir" 2>/dev/null || ! [ -w "$dir" ]; then
        log "Install directory '$dir' needs elevated permissions to be created."
        log "Attempting to create it automatically using 'sudo'..."
        
        if sudo mkdir -p "$dir" && sudo chown -R "$USER:$USER" "$dir"; then
            log "Directory '$dir' prepared and ownership assigned to $USER."
        else
            echo ""
            echo "-----------------------------------------------------------------"
            echo " ERROR [exit 2]: FAILED TO PREPARE INSTALLATION DIRECTORY"
            echo "-----------------------------------------------------------------"
            echo " The script tried to run 'sudo mkdir -p $dir' but failed."
            echo " Please create it manually and assign ownership to $USER:"
            echo "   sudo mkdir -p $dir && sudo chown \$USER:\$USER $dir"
            echo "-----------------------------------------------------------------"
            exit 2
        fi
    fi
}

# ==========================================
# MODULE: src/02_install.sh
# ==========================================
# =============================================================================
# ENVIRONMENT BOOTSTRAP
# =============================================================================

# Enables user lingering and verifies Podman socket (Ref: docs/LIBRARY_REFERENCE.md)
# shellcheck disable=SC2034
setup_lingering_and_socket() {
    PUID=$(id -u)
    PGID=$(id -g)
    USER_NAME=$(id -un)

    log "Ensuring user lingering is enabled..."
    sudo loginctl enable-linger "$USER_NAME"

    PODMAN_SOCK="/run/user/${PUID}/podman/podman.sock"

    if [ ! -S "$PODMAN_SOCK" ]; then
        log "Podman socket not found. Attempting to start it..."
        systemctl --user enable --now podman.socket 2>/dev/null || true
        for i in $(seq 1 10); do
            [ -S "$PODMAN_SOCK" ] && break
            sleep 1
        done
        if [ ! -S "$PODMAN_SOCK" ]; then
            err "Could not start Podman socket at $PODMAN_SOCK"
            exit 1
        fi
        log "Podman socket ready."
    fi
}

# Enables rootless Podman to bind privileged ports < 1024 (Ref: docs/LIBRARY_REFERENCE.md)
enable_privileged_ports() {
    local CURRENT
    CURRENT=$(sysctl -n net.ipv4.ip_unprivileged_port_start 2>/dev/null || echo "1024")

    if [ "$CURRENT" -gt 0 ] 2>/dev/null; then
        log "Enabling unprivileged binding to ports 80/443 (requires sudo)..."
        sudo sysctl -w net.ipv4.ip_unprivileged_port_start=0 >/dev/null
        if [ ! -f /etc/sysctl.d/99-unprivileged-ports.conf ]; then
            echo "net.ipv4.ip_unprivileged_port_start=0" | \
                sudo tee /etc/sysctl.d/99-unprivileged-ports.conf >/dev/null
            log "  Persisted in /etc/sysctl.d/99-unprivileged-ports.conf"
        fi
        log "  Ports 80/443 are now available for rootless containers."
    else
        log "Unprivileged port binding already enabled."
    fi
}

# =============================================================================
# CLI ARGUMENTS
# =============================================================================

# Parses CLI arguments and sets CMD_ACTION, FORCE_YES, DRY_RUN (Ref: docs/LIBRARY_REFERENCE.md)
# shellcheck disable=SC2034
parse_args() {
    CMD_ACTION=""
    FORCE_YES=0
    DRY_RUN=0

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --install)   CMD_ACTION="install" ;;
            --update)    CMD_ACTION="update" ;;
            --uninstall) CMD_ACTION="uninstall" ;;
            --start)     CMD_ACTION="start" ;;
            --yes|-y)    FORCE_YES=1 ;;
            --dry-run)   DRY_RUN=1 ; log "[DRY-RUN] mode enabled" ;;
            *) err "Unknown argument: $1"; exit 1 ;;
        esac
        shift
    done
}

# =============================================================================
# FILE MANAGEMENT
# =============================================================================

# Downloads repository files into a fresh auto-cleaned temp directory (Ref: docs/LIBRARY_REFERENCE.md)
download_repo_files() {
    local base_url="${1:?download_repo_files requires a base URL}"
    shift

    TMP_DIR=$(mktemp -d)
    trap 'rm -rf "$TMP_DIR"' EXIT

    log "Downloading files from repository..."
    for file in "$@"; do
        curl -fsSL "${base_url}/${file}" -o "${TMP_DIR}/${file}"
    done
    log "Files downloaded."
}

# Offers interactive configuration step via TTY if FORCE_YES=0 (Ref: docs/LIBRARY_REFERENCE.md)
offer_interactive_mode() {
    if [ "${FORCE_YES:-0}" -eq 1 ]; then
        return
    fi
    if [ -t 0 ]; then
        echo ""
        read -rp "Run in interactive mode? (customize all options) [y/N]: " INTERACTIVE
        if [[ "$INTERACTIVE" =~ ^[Yy]$ ]]; then
            log "Downloading interactive configurator..."
            curl -fsSL "$REPO_RAW/configure.sh" -o "$TMP_DIR/configure.sh"
            bash "$TMP_DIR/configure.sh" "$TMP_DIR/config.env"
        fi
    fi
}

# =============================================================================
# CONFIGURATION
# =============================================================================

# Auto-detects the primary host IP address (Ref: docs/LIBRARY_REFERENCE.md)
detect_host_ip() {
    if [ -z "${HOST_IP:-}" ]; then
        local INTERFACE
        INTERFACE=$(ip route | awk '/^default/ {print $5; exit}')
        HOST_IP=$(ip -4 addr show "$INTERFACE" | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | head -1)
        if [ -z "$HOST_IP" ]; then
            err "Could not determine the host IP address."
            err "Set HOST_IP in config.env and retry."
            exit 1
        fi
        log "Host IP auto-detected: $HOST_IP"
    else
        log "Host IP from config: $HOST_IP"
    fi
}

# Finds and assigns the next available IP in the internal_net range (Ref: docs/LIBRARY_REFERENCE.md)
assign_project_ip() {
    local network_name="internal_net"
    local subnet="172.170.1.0/24"
    local base_ip="172.170.1"

    # 1. Ensure network exists
    if ! podman network exists "$network_name"; then
        log "Creating internal network '$network_name' ($subnet)..."
        podman network create --subnet "$subnet" "$network_name"
    fi

    # 2. Get used IPs (active containers)
    # Using JSON + grep is more robust across Podman versions than complex templates
    local used_ips
    used_ips=$(podman network inspect "$network_name" --format '{{json .}}' 2>/dev/null | grep -oP '"IPv4Address":\s*"\K[0-9.]+' | sort -u || true)
    
    # 3. Get reserved IPs (persistent .env files in /opt and /app/data/projects)
    # We look for PROJECT_IP= variables in potential project directories
    local reserved_ips
    reserved_ips=$(grep -rh "^PROJECT_IP=" /opt/*/.env /app/data/projects/*/.env 2>/dev/null | cut -d'=' -f2- | tr -d '"' | tr -d "'" | sort -u || true)
    
    # Merge both lists to identify all occupied slots
    local all_occupied
    all_occupied=$(echo -e "${used_ips}\n${reserved_ips}" | sort -u | grep -v "^$" || true)

    # Detect the gateway IP to avoid clashing (default to .1)
    local gateway
    gateway=$(podman network inspect "$network_name" --format '{{json .}}' 2>/dev/null | grep -oP '"gateway":\s*"\K[0-9.]+' | head -1 || true)
    [ -z "$gateway" ] && gateway="${base_ip}.1"

    # 4. Find first available IP from .2 to .254
    # We skip .1 as it is the standard gateway
    for i in $(seq 2 254); do
        local candidate="${base_ip}.${i}"
        
        # Skip if it's the gateway (even if not .1)
        [[ "$candidate" == "$gateway" ]] && continue
        
        # Skip if already in use or reserved
        if echo "$all_occupied" | grep -qW "$candidate"; then
            continue
        fi
        
        PROJECT_IP="$candidate"
        log "Available IP found for project: $PROJECT_IP"
        return 0
    done

    err "No available IPs left in subnet $subnet"
    exit 1
}

# Reuses existing secrets or securely generates new hexadecimal keys (Ref: docs/LIBRARY_REFERENCE.md)
manage_credentials() {
    local install_dir="${1:?manage_credentials requires INSTALL_DIR}"
    shift
    local -a keys=("$@")
    local first_key="${keys[0]:?manage_credentials requires at least one secret name}"

    if [ -f "$install_dir/.env" ] && grep -q "^${first_key}=" "$install_dir/.env"; then
        log "Existing secrets found. Reusing..."
        for key in "${keys[@]}"; do
            local val
            val=$(grep "^${key}=" "$install_dir/.env" | cut -d '=' -f2- | sed -e 's/^"//' -e 's/"$//' -e "s/^'//" -e "s/'$//")
            printf -v "$key" '%s' "$val"
        done
    else
        log "First run detected. Generating secure secrets..."
        set +o pipefail
        for key in "${keys[@]}"; do
            local val
            val=$(tr -dc 'a-f0-9' </dev/urandom | head -c 64)
            printf -v "$key" '%s' "$val"
        done
        set -o pipefail
    fi
}

# ==========================================
# MODULE: src/03_health.sh
# ==========================================
# =============================================================================
# DEPLOYMENT VALIDATION
# =============================================================================

# Verifies specified containers are in a 'running' state post-deployment (Ref: docs/LIBRARY_REFERENCE.md)
verify_containers_running() {
    local -a REQUIRED=("$@")
    local -a FAILED=()

    log "Verifying containers are running..."
    sleep 3   # Allow containers to transition from 'created' to 'running'

    for name in "${REQUIRED[@]}"; do
        local status
        status=$(podman inspect "$name" --format '{{.State.Status}}' 2>/dev/null || echo "missing")
        if [[ "$status" != "running" ]]; then
            FAILED+=("  ✗ $name  (status: $status)")
        else
            log "  ✓ $name"
        fi
    done

    if [[ ${#FAILED[@]} -gt 0 ]]; then
        echo ""
        echo "-----------------------------------------------------------------"
        echo " ERROR [exit 3]: DEPLOYMENT FAILED — containers did not start"
        echo "-----------------------------------------------------------------"
        printf '%s\n' "${FAILED[@]}"
        echo ""
        echo " Most likely causes:"
        echo "   1. Image name not fully qualified — Podman requires a registry"
        echo "      prefix (e.g. docker.io/image:tag or ghcr.io/image:tag)."
        echo "   2. No network access to pull images from the registry."
        echo "   3. Install directory not prepared beforehand (see exit code 2)."
        echo "   4. Port conflict with another running service."
        echo ""
        echo " Diagnostic commands:"
        echo "   podman ps -a"
        echo "   podman logs <container-name>"
        echo "   journalctl --user -u <service>.service -n 80 --no-pager"
        echo "-----------------------------------------------------------------"
        exit 3
    fi

    log "All containers running."
}

# =============================================================================
# HTTP HEALTH CHECKS  (F3.4)
# =============================================================================

# Polls an HTTP endpoint for a 2xx response within a given timeout (Ref: docs/LIBRARY_REFERENCE.md)
poll_http() {
    local url="${1:?poll_http requires a URL}"
    local timeout="${2:-30}"
    local interval="${3:-2}"
    local elapsed=0

    log "Waiting for $url ..."
    while [ "$elapsed" -lt "$timeout" ]; do
        if curl -sf --max-time "$interval" "$url" >/dev/null 2>&1; then
            log "  ✓ $url"
            return 0
        fi
        sleep "$interval"
        elapsed=$((elapsed + interval))
    done

    err "Endpoint did not respond within ${timeout}s: $url"
    return 1
}

# Runs payload array of HTTP health checks and aborts on failures (Ref: docs/LIBRARY_REFERENCE.md)
check_http_health() {
    local -a FAILED=()

    log "Running HTTP health checks..."
    for entry in "$@"; do
        local label url timeout
        IFS='|' read -r label url timeout <<< "$entry"
        timeout="${timeout:-30}"
        if ! poll_http "$url" "$timeout" 2 2>/dev/null; then
            FAILED+=("  ✗ $label  ($url)")
        fi
    done

    if [[ ${#FAILED[@]} -gt 0 ]]; then
        echo ""
        echo "-----------------------------------------------------------------"
        echo " ERROR [exit 3]: HEALTH CHECKS FAILED — services not responding"
        echo "-----------------------------------------------------------------"
        printf '%s\n' "${FAILED[@]}"
        echo ""
        echo " The containers are running but the applications inside are not"
        echo " responding. Check the container logs for startup errors:"
        echo "   podman logs <container-name>"
        echo "-----------------------------------------------------------------"
        exit 3
    fi

    log "All health checks passed."
}

# ==========================================
# MODULE: src/04_uninstall.sh
# ==========================================
# =============================================================================
# ATOMIC UNINSTALLATION ENGINE
# =============================================================================

# Internal helper to extract resources from podman-compose configs (Ref: docs/LIBRARY_REFERENCE.md)
_discover_compose_resources() {
    local dir="${1:?_discover_compose_resources requires a directory}"
    local compose_file="$dir/docker-compose.yml"

    if [ -f "$compose_file" ]; then
        # Use podman-compose config to resolve syntax and show the absolute state.
        # We extract images and container names (if defined).
        # We run this in the project directory so it can find .env files if present.
        (
            cd "$dir" 2>/dev/null || exit
            # Extract images: filter 'image:', remove prefix, remove quotes
            # Extract containers: if 'container_name' is used, we get it. 
            # If not, we fall back to podman's internal project mapping.
            podman-compose config 2>/dev/null
        )
    fi
}

# Atomic uninstallation engine with dynamic discovery and manual fallbacks (Ref: docs/LIBRARY_REFERENCE.md)
uninstall_generic_service() {
    # Discovery Phase
    local -a discovered_imgs=()
    # shellcheck disable=SC2153
    local compose_file="${INSTALL_DIR}/docker-compose.yml"

    if [ -f "$compose_file" ]; then
        log "Analyzing project resources dynamically..."
        # Extract images using a robust grep/awk on the resolve config
        # We use a subshell to avoid changing the current directory
        local raw_config
        raw_config=$( (cd "$INSTALL_DIR" && podman-compose config) 2>/dev/null || true)
        
        if [ -n "$raw_config" ]; then
            while read -r img; do
                if [ -n "$img" ]; then
                    discovered_imgs+=("$img")
                fi
            done < <(echo "$raw_config" | grep 'image:' | awk '{print $2}' | tr -d '"' | tr -d "'" | sort -u)
            
            # For containers, if they aren't explicit in 'container_name', 
            # they are usually <project>_<service>_1. 
            # It's safer to use the manual list or 'podman ps' by label later.
        fi
    fi

    # Merge discovered with manual (prioritize discovered)
    if [ ${#discovered_imgs[@]} -gt 0 ]; then
        UNINSTALL_IMAGES=("${discovered_imgs[@]}")
    else
        UNINSTALL_IMAGES=("${UNINSTALL_IMAGES[@]:-}")
    fi

    # Fallback/Default arrays to empty if they are not defined, to avoid set -u crashes
    local -a local_containers=("${UNINSTALL_CONTAINERS[@]:-}")
    local -a local_volumes=("${UNINSTALL_VOLUMES[@]:-}")
    local -a local_dirs=("${UNINSTALL_DIRS[@]:-}")
    
    echo ""
    echo "=== ${UNINSTALL_SVC_NAME}: Uninstall ==="
    echo ""
    echo " WARNING: This will permanently remove:"
    echo "   - The container(s) and image(s)"
    echo "   - The systemd persistence service"
    echo ""

    if [ "${FORCE_YES:-0}" -eq 1 ]; then
        CONFIRM="UNINSTALL"
    else
        read -rp " Type 'UNINSTALL' to confirm: " CONFIRM < /dev/tty
    fi
    if [ "$CONFIRM" != "UNINSTALL" ]; then
        log "Uninstall cancelled."
        exit 0
    fi

    echo ""
    log "Stopping systemd service..."
    systemctl --user stop "$UNINSTALL_SYSTEMD" 2>/dev/null || true
    systemctl --user disable "$UNINSTALL_SYSTEMD" 2>/dev/null || true
    rm -f ~/.config/systemd/user/"$UNINSTALL_SYSTEMD"
    systemctl --user daemon-reload

    log "Removing container(s)..."
    # If we have manual containers, remove them. 
    # Also, try to remove by project label if podman-compose was used.
    for c in "${local_containers[@]}"; do
        if [ -n "$c" ]; then
            podman rm -f "$c" 2>/dev/null || true
        fi
    done
    
    # Advanced: Try to find containers by the directory name if it matches podman-compose pattern
    local project_name
    project_name=$(basename "$INSTALL_DIR" | tr -d '-') 
    podman ps -a --filter "label=com.docker.compose.project=$project_name" --format "{{.Names}}" | xargs -r podman rm -f 2>/dev/null || true

    log "Removing image(s)..."
    for i in "${UNINSTALL_IMAGES[@]}"; do
        if [ -n "$i" ]; then
            podman rmi "$i" 2>/dev/null || true
        fi
    done

    echo ""
    if [ "${FORCE_YES:-0}" -eq 1 ]; then
        DELETE_DATA="y"
    else
        if [ ${#local_volumes[@]} -gt 0 ] && [ -n "${local_volumes[0]:-}" ]; then
            echo " Persistent volumes connected to this service:"
            for v in "${local_volumes[@]}"; do [ -n "$v" ] && echo "   - $v"; done
        fi
        if [ ${#local_dirs[@]} -gt 0 ] && [ -n "${local_dirs[0]:-}" ]; then
            echo " Data directories connected to this service:"
            for d in "${local_dirs[@]}"; do [ -n "$d" ] && echo "   - $d"; done
        fi
        [ -n "${UNINSTALL_DATA_WARN:-}" ] && echo " $UNINSTALL_DATA_WARN"
        echo ""
        read -rp " Delete ALL data and the installation directory ($INSTALL_DIR)? [y/N]: " DELETE_DATA < /dev/tty
    fi

    if [[ "$DELETE_DATA" =~ ^[Yy]$ ]]; then
        log "Removing configuration, data, and installation directory..."
        if [ ${#local_volumes[@]} -gt 0 ] && [ -n "${local_volumes[0]:-}" ]; then
            for v in "${local_volumes[@]}"; do 
                if [ -n "$v" ]; then
                    podman volume rm "$v" 2>/dev/null || true
                fi
            done
        fi
        if [ ${#local_dirs[@]} -gt 0 ] && [ -n "${local_dirs[0]:-}" ]; then
            for d in "${local_dirs[@]}"; do [ -n "$d" ] && sudo rm -rf "$d"; done
        fi
        sudo rm -rf "${INSTALL_DIR:?}"
        log "All data and directory removed."
    else
        if [ ${#local_volumes[@]} -gt 0 ] && [ -n "${local_volumes[0]:-}" ] || [ ${#local_dirs[@]} -gt 0 ] && [ -n "${local_dirs[0]:-}" ]; then
            log "Data preserved."
        fi
        sudo rm -f "${INSTALL_DIR:?}/.env" "${INSTALL_DIR:?}/config.env" "${INSTALL_DIR:?}/docker-compose.yml"
        log "Config files cleaned up, but installation directory ($INSTALL_DIR) preserved."
    fi

    echo ""
    echo "================================================================="
    echo " ${UNINSTALL_SVC_NAME} has been uninstalled."
    echo "================================================================="
}

# ==========================================
# MODULE: src/05_arcane.sh
# ==========================================
# =============================================================================
# ARCANE INTEGRATION
# =============================================================================

# Syncs service configurations to Arcane's dashboard and patches labels (Ref: docs/LIBRARY_REFERENCE.md)
register_arcane_project() {
    local project_name="${1:?register_arcane_project requires a project name}"
    local install_dir="${2:?register_arcane_project requires an installation directory}"
    local arcane_projects_dir="/opt/arcane/projects"

    if [[ "$project_name" == "arcane" ]]; then
        log "Skipping Arcane self-registration to prevent circular self-management."
        return 0
    fi

    log "Registering project '$project_name' in Arcane..."

    # Ensure the parent directory exists
    if ! [ -d "$arcane_projects_dir/$project_name" ]; then
        if sudo mkdir -p "$arcane_projects_dir/$project_name" && sudo chown -R "$USER:$USER" "$arcane_projects_dir" 2>/dev/null; then
            log "  Created Arcane projects directory: $arcane_projects_dir/$project_name"
        else
            warn "  Could not create Arcane projects directory. Skipping registration."
            return 1
        fi
    fi

    # Copy files instead of symlinking. Symlinks break because they point to paths 
    # outside the Arcane container (e.g. /opt/supabase) which are not mounted.
    cp -f "$install_dir/docker-compose.yml" "$arcane_projects_dir/$project_name/"
    [ -f "$install_dir/.env" ] && cp -f "$install_dir/.env" "$arcane_projects_dir/$project_name/"
    
    # CRITICAL FIX: Arcane matches containers to projects by reading the 
    # 'com.docker.compose.project.working_dir' label from the running container
    # and looking for a docker-compose.yml in that EXACT directory inside its own container.
    # Since podman runs on the host at /opt/<slug>, the label says /opt/<slug>.
    # But inside Arcane, the file is at /app/data/projects/<slug>.
    # We must patch the copied compose file to FORCE the working_dir label
    # to match the container's internal path, or Arcane will never link them.
    sed -i -E "s|com.docker.compose.project.working_dir=.*|com.docker.compose.project.working_dir=/app/data/projects/$project_name|g" "$arcane_projects_dir/$project_name/docker-compose.yml" || true
    
    # If the label wasn't there to replace, inject it under the first 'labels:' section
    if ! grep -q "com.docker.compose.project.working_dir" "$arcane_projects_dir/$project_name/docker-compose.yml"; then
        sed -i "0,/labels:/s//labels:\n      - \"com.docker.compose.project.working_dir=\/app\/data\/projects\/$project_name\"/g" "$arcane_projects_dir/$project_name/docker-compose.yml" || true
    fi

    log "  Config synced to Arcane: $arcane_projects_dir/$project_name"
}

