#!/bin/bash
set -euo pipefail

# ==============================================================================
# ARCANE — Management Script
# Single entry point for installing, starting, updating, and uninstalling Arcane.
#
# Usage:
#   bash arcane.sh                                (local, interactive)
#   curl -fsSL <raw_url>/arcane.sh | bash          (remote, automatic)
#
# Re-running this script on an existing installation is safe.
# ==============================================================================

GIT_BRANCH="${GIT_BRANCH:-main}"
REPO_BASE="${REPO_BASE:-https://raw.githubusercontent.com/Carlosjcfr/docker-develop/$GIT_BRANCH}"
REPO_RAW="$REPO_BASE/projects/arcane"

# =============================================================================
# SHARED LIBRARY
# Source common functions: logging, guards, env bootstrap, validation.
# Set LIB_LOCAL to an absolute path to use a local copy (development only).
# =============================================================================

_LIB_URL="$REPO_BASE/lib/lib.sh"
# shellcheck source=../../lib/lib.sh
if [[ -n "${LIB_LOCAL:-}" && -f "$LIB_LOCAL" ]]; then
    source "$LIB_LOCAL"
else
    source <(curl -fsSL "$_LIB_URL") || {
        echo "[ERROR] Could not download shared library from: $_LIB_URL" >&2
        echo "        Check your network connection and try again." >&2
        exit 1
    }
fi
unset _LIB_URL

# =============================================================================
# SERVICE-SPECIFIC FUNCTIONS
# =============================================================================

# Returns 0 if an existing Arcane installation is detected, 1 otherwise.
check_existing_installation() {
    local dir="${1:-/opt/arcane}"
    if [ -f "$dir/.env" ] && podman container exists arcane 2>/dev/null; then
        return 0
    fi
    return 1
}

load_configuration() {
    # shellcheck source=/dev/null
    source "$TMP_DIR/config.env"

    # Security guard: abort if a secret key is found in the repo config file
    check_secrets_not_in_config "$TMP_DIR/config.env" ENCRYPTION_KEY JWT_SECRET

    INSTALL_DIR="${INSTALL_DIR:-/opt/arcane}"
    APP_PORT="${APP_PORT:-3552}"
    PACKAGE_VERSION="${PACKAGE_VERSION:-latest}"
    LOG_LEVEL="${LOG_LEVEL:-info}"
    ENVIRONMENT="${ENVIRONMENT:-production}"
    GIN_MODE="${GIN_MODE:-release}"
    TZ="${TZ:-UTC}"
    DATABASE_URL="${DATABASE_URL:-file:data/arcane.db?_pragma=journal_mode(WAL)&_pragma=busy_timeout(2500)&_txlock=immediate}"
    ALLOW_DOWNGRADE="${ALLOW_DOWNGRADE:-false}"
    JWT_REFRESH_EXPIRY="${JWT_REFRESH_EXPIRY:-168h}"
    FILE_PERM="${FILE_PERM:-0644}"
    DIR_PERM="${DIR_PERM:-0755}"
    TLS_ENABLED="${TLS_ENABLED:-false}"
    TLS_CERT_FILE="${TLS_CERT_FILE:-}"
    TLS_KEY_FILE="${TLS_KEY_FILE:-}"
    AGENT_MODE="${AGENT_MODE:-false}"
    AGENT_TOKEN="${AGENT_TOKEN:-}"

    ARCANE_ICON="${ARCANE_ICON:-si:arcane}"
    ARCANE_CATEGORY="${ARCANE_CATEGORY:-Management}"

    log "Configuration loaded (INSTALL_DIR=$INSTALL_DIR, APP_PORT=$APP_PORT)."
}

generate_runtime_env() {
    log "Generating runtime .env file..."
    local OLD_UMASK
    OLD_UMASK=$(umask)
    umask 177

    cat <<EOF > "$INSTALL_DIR/.env"
# =============================================================================
# ARCANE — Runtime Environment Variables
# Auto-generated by arcane.sh — do NOT edit manually.
# To change settings, edit config.env in the repository and re-run arcane.sh.
# =============================================================================

# --- Core (auto-generated) ---
HOST_IP="$HOST_IP"
PUID="$PUID"
PGID="$PGID"
APP_PORT="$APP_PORT"
APP_URL="http://$HOST_IP:$APP_PORT"
PODMAN_SOCK="$PODMAN_SOCK"
ENCRYPTION_KEY="$ENCRYPTION_KEY"
JWT_SECRET="$JWT_SECRET"

# --- Application (from config.env) ---
PACKAGE_VERSION="$PACKAGE_VERSION"
ENVIRONMENT="$ENVIRONMENT"
GIN_MODE="$GIN_MODE"
LOG_LEVEL="$LOG_LEVEL"
TZ="$TZ"

# --- Database ---
DATABASE_URL="$DATABASE_URL"
ALLOW_DOWNGRADE="$ALLOW_DOWNGRADE"

# --- Security ---
JWT_REFRESH_EXPIRY="$JWT_REFRESH_EXPIRY"
FILE_PERM="$FILE_PERM"
DIR_PERM="$DIR_PERM"

# --- TLS ---
TLS_ENABLED="$TLS_ENABLED"
TLS_CERT_FILE="$TLS_CERT_FILE"
TLS_KEY_FILE="$TLS_KEY_FILE"

# --- Agent ---
AGENT_MODE="$AGENT_MODE"
AGENT_TOKEN="$AGENT_TOKEN"

# --- Arcane ---
ARCANE_ICON="$ARCANE_ICON"
ARCANE_CATEGORY="$ARCANE_CATEGORY"
EOF

    umask "$OLD_UMASK"
    log ".env file ready (permissions 600)."
}

prepare_directories() {
    log "Preparing data directories..."
    check_install_dir_writable "$INSTALL_DIR"
    mkdir -p "$INSTALL_DIR" "${INSTALL_DIR}/data" "${INSTALL_DIR}/projects"
    sudo chown -R "${PUID}:${PGID}" "${INSTALL_DIR}/data" "${INSTALL_DIR}/projects"
    log "Directories ready."
}

deploy_and_persist() {
    log "Starting services with podman-compose..."
    cd "$INSTALL_DIR"
    # podman-compose up -d exits 0 even on total failure — verify_containers_running
    # performs the real post-deploy check.
    podman-compose up -d > /dev/null 2>&1

    verify_containers_running arcane

    log "Configuring systemd service for persistence..."
    mkdir -p ~/.config/systemd/user/

    # Handwritten unit — replaces deprecated 'podman generate systemd' (Podman 5+).
    # Type=oneshot + RemainAfterExit=yes: compose forks and exits immediately, but
    # containers keep running. systemd tracks the service as active until ExecStop runs.
    cat <<EOF > ~/.config/systemd/user/container-arcane.service
[Unit]
Description=Arcane Container Management UI (podman-compose)
Wants=network-online.target
After=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=$INSTALL_DIR
ExecStart=$(command -v podman-compose) up -d
ExecStop=$(command -v podman-compose) down
TimeoutStartSec=120
TimeoutStopSec=30

[Install]
WantedBy=default.target
EOF

    systemctl --user daemon-reload
    systemctl --user enable --now container-arcane.service
}

print_success() {
    echo ""
    echo "================================================================="
    echo " ARCANE deployed and secured with systemd."
    echo " Access it at: http://$HOST_IP:$APP_PORT"
    echo ""
    echo " The container will now persist after logout and on VM reboots."
    echo ""
    echo " Useful commands:"
    echo "   Status:  systemctl --user status container-arcane.service"
    echo "   Logs:    podman logs -f arcane"
    echo "   Restart: systemctl --user restart container-arcane.service"
    echo "================================================================="
}

# =============================================================================
# ACTIONS
# =============================================================================

do_install() {
    echo ""
    echo "=== ARCANE: Fresh Installation ==="
    echo ""

    download_repo_files "$REPO_RAW" config.env docker-compose.yml
    offer_interactive_mode
    load_configuration
    detect_host_ip
    manage_credentials "$INSTALL_DIR" ENCRYPTION_KEY JWT_SECRET
    setup_lingering_and_socket
    prepare_directories

    mv -f "$TMP_DIR/config.env"         "$INSTALL_DIR/config.env"
    mv -f "$TMP_DIR/docker-compose.yml" "$INSTALL_DIR/docker-compose.yml"

    generate_runtime_env
    deploy_and_persist
    register_arcane_project "arcane" "$INSTALL_DIR"
    print_success

}

do_start() {
    echo ""
    echo "=== ARCANE: Starting ==="
    echo ""

    if systemctl --user is-active --quiet container-arcane.service 2>/dev/null; then
        log "Arcane is already running."
    else
        systemctl --user start container-arcane.service
        log "Arcane started successfully."
    fi

    if [ -f "$INSTALL_DIR/.env" ]; then
        local ip port
        ip=$(grep "^HOST_IP=" "$INSTALL_DIR/.env" | cut -d '=' -f2- || echo "unknown")
        port=$(grep "^APP_PORT=" "$INSTALL_DIR/.env" | cut -d '=' -f2- || echo "3552")
        log "Access it at: http://$ip:$port"
    fi
}

do_update() {
    echo ""
    echo "=== ARCANE: Updating ==="
    echo ""

    download_repo_files "$REPO_RAW" config.env docker-compose.yml
    offer_interactive_mode
    load_configuration
    detect_host_ip
    manage_credentials "$INSTALL_DIR" ENCRYPTION_KEY JWT_SECRET
    setup_lingering_and_socket
    prepare_directories

    mv -f "$TMP_DIR/config.env"         "$INSTALL_DIR/config.env"
    mv -f "$TMP_DIR/docker-compose.yml" "$INSTALL_DIR/docker-compose.yml"

    generate_runtime_env

    log "Pulling latest Arcane image..."
    cd "$INSTALL_DIR"
    podman-compose pull > /dev/null 2>&1

    deploy_and_persist
    register_arcane_project "arcane" "$INSTALL_DIR"
    print_success

}

do_uninstall() {
    INSTALL_DIR="${INSTALL_DIR:-/opt/arcane}"
    UNINSTALL_SVC_NAME="ARCANE"
    UNINSTALL_SYSTEMD="container-arcane.service"
    UNINSTALL_CONTAINERS=("arcane")
    UNINSTALL_IMAGES=("ghcr.io/getarcaneapp/arcane:${PACKAGE_VERSION:-latest}")
    UNINSTALL_VOLUMES=()
    UNINSTALL_DIRS=("${INSTALL_DIR}/data" "${INSTALL_DIR}/projects")
    UNINSTALL_DATA_WARN="WARNING: Internal database and all arcane projects will be lost!"

    uninstall_generic_service
}

# =============================================================================
# MAIN
# =============================================================================

root_protection
check_dependencies curl podman-compose

parse_args "$@"

if [ -n "$CMD_ACTION" ]; then
    case "$CMD_ACTION" in
        install)   do_install ;;
        start)     do_start ;;
        update)    do_update ;;
        uninstall) do_uninstall ;;
        *) err "Invalid action."; exit 1 ;;
    esac
    exit 0
fi

if check_existing_installation "/opt/arcane"; then
    if [ -t 0 ] && [ "$FORCE_YES" -eq 0 ]; then
        echo ""
        echo "================================================================="
        echo " ARCANE — Management"
        echo "================================================================="
        echo " Existing installation detected at /opt/arcane"
        echo ""
        echo "   1) Start      — Start the existing container"
        echo "   2) Update     — Download latest config and redeploy"
        echo "   3) Uninstall  — Remove container, service, and data"
        echo "   0) Cancel"
        echo ""
        read -rp " Select [0-3]: " ACTION

        case "$ACTION" in
            1) do_start ;;
            2) do_update ;;
            3) do_uninstall ;;
            0) log "Cancelled."; exit 0 ;;
            *) err "Invalid option."; exit 1 ;;
        esac
    else
        log "Existing installation detected. Running automatic update..."
        do_update
    fi
else
    do_install
fi
