#!/bin/bash
set -euo pipefail

# ==============================================================================
# ARCANE - Interactive Configuration Assistant
# Prompts for each configurable option and generates a local config.env.
# Called automatically by install.sh when interactive mode is selected.
#
# Usage (standalone):  bash configure.sh [base_config_env_path]
# Usage (from install): called internally — do not run manually.
# ==============================================================================

# Base config.env to read defaults from (passed as argument or current dir)
BASE_CONFIG="${1:-config.env}"

# --- Load defaults from base config.env if available --------------------------
INSTALL_DIR="/opt/arcane"
HOST_IP=""
APP_PORT="3552"
ENVIRONMENT="production"
GIN_MODE="release"
LOG_LEVEL="info"
TZ="Europe/Madrid"
JWT_REFRESH_EXPIRY="168h"
FILE_PERM="0644"
DIR_PERM="0755"
TLS_ENABLED="false"
TLS_CERT_FILE=""
TLS_KEY_FILE=""
AGENT_MODE="false"
AGENT_TOKEN=""

if [ -f "$BASE_CONFIG" ]; then
    # shellcheck source=/dev/null
    source "$BASE_CONFIG"
fi

# --- Helper: prompt with default value ----------------------------------------
# Usage: ask "Prompt text" DEFAULT_VALUE
# Returns the user input or the default if empty.
ask() {
    local prompt="$1"
    local default="$2"
    local value

    if [ -n "$default" ]; then
        read -rp "  $prompt [$default]: " value
    else
        read -rp "  $prompt: " value
    fi
    echo "${value:-$default}"
}

# --- Interactive prompts ------------------------------------------------------
echo ""
echo "================================================================="
echo " ARCANE - Interactive Configuration"
echo "================================================================="
echo " Press ENTER to accept the default value shown in brackets."
echo ""

echo " ── Deployment ──"
INSTALL_DIR=$(ask "Installation directory" "$INSTALL_DIR")
HOST_IP=$(ask "Host IP (empty = auto-detect)" "$HOST_IP")
APP_PORT=$(ask "Web UI port" "$APP_PORT")

echo ""
echo " ── Application ──"
ENVIRONMENT=$(ask "Environment (production/development)" "$ENVIRONMENT")
GIN_MODE=$(ask "Framework mode (release/debug)" "$GIN_MODE")
LOG_LEVEL=$(ask "Log level (debug/info/warn/error)" "$LOG_LEVEL")
TZ=$(ask "Timezone" "$TZ")

echo ""
echo " ── Security ──"
JWT_REFRESH_EXPIRY=$(ask "JWT refresh token expiry" "$JWT_REFRESH_EXPIRY")
FILE_PERM=$(ask "File permissions (octal)" "$FILE_PERM")
DIR_PERM=$(ask "Directory permissions (octal)" "$DIR_PERM")

echo ""
echo " ── TLS (skip if behind a reverse proxy) ──"
TLS_ENABLED=$(ask "Enable direct TLS (true/false)" "$TLS_ENABLED")
if [ "$TLS_ENABLED" = "true" ]; then
    TLS_CERT_FILE=$(ask "Path to TLS certificate" "$TLS_CERT_FILE")
    TLS_KEY_FILE=$(ask "Path to TLS private key" "$TLS_KEY_FILE")
fi

echo ""
echo " ── Agent Mode (for remote management) ──"
AGENT_MODE=$(ask "Enable agent mode (true/false)" "$AGENT_MODE")
if [ "$AGENT_MODE" = "true" ]; then
    AGENT_TOKEN=$(ask "Agent API token" "$AGENT_TOKEN")
fi

# --- Write config.env ---------------------------------------------------------
# Output path: same directory as the base config or current directory
OUTPUT_DIR="$(dirname "$BASE_CONFIG")"
OUTPUT_FILE="${OUTPUT_DIR}/config.env"

cat <<EOF > "$OUTPUT_FILE"
# =============================================================================
# ARCANE - Configuration
# =============================================================================
# Generated by configure.sh (interactive mode).
#
# ⚠️ DO NOT ADD SECRETS HERE — this file is public.
#    Secrets (ENCRYPTION_KEY, JWT_SECRET) are auto-generated by install.sh.
# =============================================================================

# --- Deployment ---------------------------------------------------------------

INSTALL_DIR=$INSTALL_DIR
HOST_IP=$HOST_IP
APP_PORT=$APP_PORT

# --- Application --------------------------------------------------------------

ENVIRONMENT=$ENVIRONMENT
GIN_MODE=$GIN_MODE
LOG_LEVEL=$LOG_LEVEL
TZ=$TZ

# --- Security -----------------------------------------------------------------

JWT_REFRESH_EXPIRY=$JWT_REFRESH_EXPIRY
FILE_PERM=$FILE_PERM
DIR_PERM=$DIR_PERM

# --- TLS ----------------------------------------------------------------------

TLS_ENABLED=$TLS_ENABLED
TLS_CERT_FILE=$TLS_CERT_FILE
TLS_KEY_FILE=$TLS_KEY_FILE

# --- Agent Mode ---------------------------------------------------------------

AGENT_MODE=$AGENT_MODE
AGENT_TOKEN=$AGENT_TOKEN
EOF

echo ""
echo "================================================================="
echo " Configuration saved. Continuing with installation..."
echo "================================================================="
echo ""
