#!/bin/bash
set -euo pipefail

# ==============================================================================
# ARCANE - Deployment Script
# ==============================================================================

# --- Dependency checks --------------------------------------------------------
if ! command -v podman-compose &> /dev/null; then
    echo "ERROR: 'podman-compose' not found. Please install it before continuing." >&2
    exit 1
fi

# --- HOST IP MAPPING ----------------------------------------------------------
# Detects the IP address from the default network interface.
# If IPs are static and known, replace the lines below with:
#   HOST_IP="192.168.X.X"
INTERFACE=$(ip route | awk '/^default/ {print $5; exit}')
HOST_IP=$(ip -4 addr show "$INTERFACE" | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | head -1)

if [ -z "$HOST_IP" ]; then
    echo "ERROR: Could not determine the host IP address." >&2
    exit 1
fi

echo "Host IP detected: $HOST_IP -> Checking credentials..."

# --- CREDENTIAL MANAGEMENT ----------------------------------------------------
# If .env already exists and contains ENCRYPTION_KEY, secrets are reused
# to avoid breaking sessions on restarts. PODMAN_SOCK and HOST_IP are always refreshed.
if [ -f .env ] && grep -q "^ENCRYPTION_KEY=" .env; then
    echo "Existing .env file found. Reusing current secrets..."
    ENCRYPTION_KEY=$(grep "^ENCRYPTION_KEY=" .env | cut -d '=' -f2-)
    JWT_SECRET=$(grep "^JWT_SECRET=" .env          | cut -d '=' -f2-)
else
    echo "First run detected. Generating secure encryption keys..."
    # 64-character hex keys for Arcane
    ENCRYPTION_KEY=$(tr -dc 'a-f0-9' </dev/urandom | head -c 64)
    JWT_SECRET=$(tr -dc 'a-f0-9'     </dev/urandom | head -c 64)
fi

# --- UID/GID & PODMAN SOCKET RESOLUTION --------------------------------------
PUID=$(id -u)
PGID=$(id -g)

# Rootless Podman socket path — unique per user, resolved at deploy time.
# This is written to .env so docker-compose.yml can reference it as ${PODMAN_SOCK}.
PODMAN_SOCK="/run/user/${PUID}/podman/podman.sock"

if [ ! -S "$PODMAN_SOCK" ]; then
    echo "Podman socket not found. Attempting to enable and start it..."
    if systemctl --user enable --now podman.socket 2>/dev/null; then
        # Wait up to 10 seconds for the socket to appear
        for i in $(seq 1 10); do
            [ -S "$PODMAN_SOCK" ] && break
            sleep 1
        done
    fi
    if [ ! -S "$PODMAN_SOCK" ]; then
        echo "ERROR: Could not start Podman socket at $PODMAN_SOCK" >&2
        echo "       Try manually: systemctl --user enable --now podman.socket" >&2
        exit 1
    fi
    echo "Podman socket ready."
fi

# --- WRITE .env (restricted permissions 600) ----------------------------------
echo "Generating .env file..."

# umask 177 ensures the file is created with 600 permissions (owner read/write only)
OLD_UMASK=$(umask)
umask 177

cat <<EOF > .env
# =============================================================================
# ARCANE - Environment Variables
# Auto-generated by start.sh — do NOT edit manually.
# =============================================================================

HOST_IP=$HOST_IP
PUID=$PUID
PGID=$PGID
APP_URL=http://$HOST_IP:3552

# Podman rootless socket (resolved at deploy time)
PODMAN_SOCK=$PODMAN_SOCK

# Security
ENCRYPTION_KEY=$ENCRYPTION_KEY
JWT_SECRET=$JWT_SECRET
EOF

# Restore original umask
umask "$OLD_UMASK"

echo ".env file ready with 600 permissions."

# --- PREPARE BIND-MOUNT DIRECTORIES ------------------------------------------
# These directories are mounted into the container. They must exist before
# podman-compose starts, otherwise Podman creates them as root.
echo "Preparing data directories..."
mkdir -p ./data ./stacks
echo "Directories ready: ./data  ./stacks"

# --- DEPLOY -------------------------------------------------------------------
echo "Starting services with podman-compose..."
podman-compose up -d

echo ""
echo "================================================================="
echo " ARCANE deployed successfully."
echo " Access it at: http://$HOST_IP:3552"
echo "================================================================="
