#!/bin/bash
set -euo pipefail

# ==============================================================================
# ARCANE - Deployment Script
# ==============================================================================

INSTALL_DIR="/opt/arcane"

# --- Dependency checks --------------------------------------------------------
if [[ $EUID -eq 0 ]]; then
   echo "-----------------------------------------------------------------"
   echo " ERROR: DO NOT RUN THIS SCRIPT WITH SUDO"
   echo "-----------------------------------------------------------------"
   echo " To maintain a Rootless Podman installation, this script must be"
   echo " executed as a normal user (admin-sigergy)."
   echo ""
   echo " PLEASE RETRY WITH: bash start.sh"
   echo "-----------------------------------------------------------------"
   exit 1
fi

if ! command -v podman-compose &> /dev/null; then
    echo "ERROR: 'podman-compose' not found. Please install it before continuing." >&2
    exit 1
fi

# --- HOST IP MAPPING ----------------------------------------------------------
# Detects the IP address from the default network interface.
# If IPs are static and known, replace the lines below with:
#   HOST_IP="192.168.X.X"
INTERFACE=$(ip route | awk '/^default/ {print $5; exit}')
HOST_IP=$(ip -4 addr show "$INTERFACE" | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | head -1)

if [ -z "$HOST_IP" ]; then
    echo "ERROR: Could not determine the host IP address." >&2
    exit 1
fi

echo "Host IP detected: $HOST_IP -> Checking credentials..."

# --- CREDENTIAL MANAGEMENT ----------------------------------------------------
# If .env already exists and contains ENCRYPTION_KEY, secrets are reused
# to avoid breaking sessions on restarts. PODMAN_SOCK and HOST_IP are always refreshed.
if [ -f .env ] && grep -q "^ENCRYPTION_KEY=" .env; then
    echo "Existing .env file found. Reusing current secrets..."
    ENCRYPTION_KEY=$(grep "^ENCRYPTION_KEY=" .env | cut -d '=' -f2-)
    JWT_SECRET=$(grep "^JWT_SECRET=" .env          | cut -d '=' -f2-)
else
    echo "First run detected. Generating secure encryption keys..."
    # 64-character hex keys for Arcane.
    # pipefail is temporarily disabled: head -c closes the pipe early causing
    # SIGPIPE on tr, which would silently kill the script under set -o pipefail.
    set +o pipefail
    ENCRYPTION_KEY=$(tr -dc 'a-f0-9' </dev/urandom | head -c 64)
    JWT_SECRET=$(tr -dc 'a-f0-9'     </dev/urandom | head -c 64)
    set -o pipefail
fi

# --- UID/GID & PODMAN SOCKET RESOLUTION --------------------------------------
PUID=$(id -u)
PGID=$(id -g)
USER_NAME=$(id -un)

# 1. Enable lingering for the user to keep processes running after logout
echo "Ensuring user lingering is enabled..."
sudo loginctl enable-linger "$USER_NAME"

# Rootless Podman socket path — unique per user, resolved at deploy time.
# ... (rest of socket logic) ...
PODMAN_SOCK="/run/user/${PUID}/podman/podman.sock"

if [ ! -S "$PODMAN_SOCK" ]; then
    echo "Podman socket not found. Attempting to enable and start it..."
    systemctl --user enable --now podman.socket 2>/dev/null || true
    # Wait up to 10 seconds for the socket to appear
    for i in $(seq 1 10); do
        [ -S "$PODMAN_SOCK" ] && break
        sleep 1
    done
    if [ ! -S "$PODMAN_SOCK" ]; then
        echo "ERROR: Could not start Podman socket at $PODMAN_SOCK" >&2
        exit 1
    fi
    echo "Podman socket ready."
fi

# --- WRITE .env (restricted permissions 600) ----------------------------------
# ... (existing umask and cat logic) ...
echo "Generating .env file..."
OLD_UMASK=$(umask)
umask 177
cat <<EOF > .env
# =============================================================================
# ARCANE - Environment Variables
# Auto-generated by start.sh — do NOT edit manually.
# =============================================================================

HOST_IP=$HOST_IP
PUID=$PUID
PGID=$PGID
APP_URL=http://$HOST_IP:3552
PODMAN_SOCK=$PODMAN_SOCK
ENCRYPTION_KEY=$ENCRYPTION_KEY
JWT_SECRET=$JWT_SECRET
EOF
umask "$OLD_UMASK"

# --- PREPARE BIND-MOUNT DIRECTORIES ------------------------------------------
echo "Preparing data directories..."
mkdir -p "${INSTALL_DIR}/data" "${INSTALL_DIR}/projects"
# Note: chown might need sudo if directories were created by another user previously.
sudo chown -R "${PUID}:${PGID}" "${INSTALL_DIR}/data" "${INSTALL_DIR}/projects"

# --- DEPLOY & PERSISTENCE (Systemd) -------------------------------------------
echo "Starting services with podman-compose..."
podman-compose up -d

echo "Configuring systemd service for persistence..."
# Create directory for local systemd user units if it doesn't exist
mkdir -p ~/.config/systemd/user/

# Generate systemd unit for the container named 'arcane'
# We use --new to ensure the container is recreated from the image on service start
podman generate systemd --name arcane --files --new --restart-policy=always --dest ~/.config/systemd/user/

# Reload systemd to recognize the new unit and enable it
systemctl --user daemon-reload
systemctl --user enable --now container-arcane.service

echo ""
echo "================================================================="
echo " ARCANE deployed and secured with systemd."
echo " Access it at: http://$HOST_IP:3552"
echo " The container will now persist after logout and on reboots."
echo "================================================================="
